name: CD

on:
  workflow_dispatch:
    inputs:
      version-num:
        description: 'the product version number'
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/ci-reusable.yaml
    with:
      version-num: ${{ inputs.version-num }}
      bin-artifact: 'bin'
  
  deploy:  
    runs-on: windows-latest
    needs: build
    
    env:
      installer-file: 'src/installer/installer.aip'      
      output-dir: 'src/installer/bin'
      package-name: pancake-${{ inputs.version-num }}.msi
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2    
        
      - name: download bin
        uses: actions/download-artifact@v3
        with:
          name: 'bin'
          path: src/pancake/bin/
          
      - name: make installer bin
        run: mkdir ${{ env.output-dir }}
        
      - name: create installer
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-version: '20.2'
          aip-path: ${{ env.installer-file }}
          aip-build-name: 'AnyCPU_Release'
          aip-package-name: ${{ env.package-name }}
          aip-output-dir: ${{ env.output-dir }}
          aip-commands: |
            SetVersion ${{ inputs.version-num }}
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: installer
          path: ${{ env.output-dir }}/${{ env.package-name }}
