name: CI - Reusable

on: 
  workflow_call:
    inputs:
      version-num:
        description: 'the product version number'
        required: true
        type: string
      bin-artifact:
        description: 'a copy of the bin folder after a build'
        default: 'bin'
        required: false
        type: string      

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:      
      Solution_Path: pancake.sln      
      Wpf_Project_Path: src/pancake/pancake.csproj      
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2      
    
    # maybe add nerdbank versioning? https://github.com/AArnott/nbgv
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "7.0.x"
        
    #- name: Add MSBuild
    #  uses: microsoft/setup-msbuild@v1.1
    #  with: 
    #    # 17.4 is required for the source code generator to work.
    #    vs-version: '[17.4'

    #- name: Restore
    #  run: MSBuild  ${{ env.Solution_Path }} /t:Restore
      
    #- name: Build
    #  run: MSBuild  ${{ env.Solution_Path }} /p:Configuration=Release /p:Version=${{ inputs.version-num }}

    - name: dotnet build
      run: dotnet build -p:EnableWindowsTargeting=true
          
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.bin-artifact }}
        path: src/pancake/bin/
        

