name: CI - Reusable

on: 
  workflow_call:
    inputs:
      version-num:
        description: 'the product version number'
        required: true
        type: string
      bin-artifact:
        description: 'a copy of the bin folder after a build'
        default: 'bin'
        required: false
        type: string      

jobs:
  build:
    runs-on: windows-latest
    
    env:      
      Solution_Path: pancake.sln      
      Wpf_Project_Path: src/pancake/pancake.csproj      
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3.5.0
    
    # maybe add nerdbank versioning? https://github.com/AArnott/nbgv
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: "7.0.x"

    - name: dotnet build
      run: dotnet build -p:Configuration=Release -p:Version=${{ inputs.version-num }}
          
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.bin-artifact }}
        path: src/pancake/bin/
