name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    env:      
      Solution_Path: src/pancake.sln      
      Wpf_Project_Path: src/pancake/pancake.csproj      
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2      
    
    # maybe add nerdbank versioning? https://github.com/AArnott/nbgv
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"
        
    - name: Add MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with: 
        # 17.4 is required for the source code generator to work.
        vs-version: '[17.4'

    - name: Restore
      run: MSBuild  ${{ env.Solution_Path }} /t:Restore
      
    - name: Build
      run: MSBuild  ${{ env.Solution_Path }} /p:Version=1.2.4
