name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    env:      
      Solution_Path: src/pancake.sln      
      Wpf_Project_Path: src/pancake/pancake.csproj      
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2      
    
    # maybe add nerdbank versioning? https://github.com/AArnott/nbgv
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"
        
    - name: Add MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with: 
        vs-version: '[17.4'
    
    - name: Build
      run: dotnet build /p:Version=1.0.0 ${{ env.Solution_Path }}
