name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    env:      
      Solution_Path: src/pancake.sln      
      Wpf_Project_Path: src/pancake/pancake.csproj      
      
    steps:
    
    # maybe add nerdbank versioning? https://github.com/AArnott/nbgv
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      
    - name: .NET Restore
      run: dotnet restore ${{ env.Solution_Path }} --runtime $env:RuntimeIdentifier
      env:
        RuntimeIdentifier: win-x64
        
    - name: Build
      run: dotnet build /p:Version=1.0.0
